language: python

python:
    - "3.6"
    - "3.7"

install:
    - "python setup.py install"
    - "pip install coverage"
    - "pip install coveralls"

script:
    - "coverage run --source=wespe setup.py test"

after_success:
    coveralls
