jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: build release distributions
        run: |
          python setup.py build

      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: build/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment:
      name: pypi
      url: https://pypi.org/p/wespe
    permissions:
      id-token: write

    steps:
      - name: Retrieve release build
        uses: actions/download-artifact@v4
        with:
          name: release-build
          path: build/

      - name: Publish release build to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
